version: '3.8'

services:
  migrations:
    build:  ./db/migrations
    env_file:
      - .env
    depends_on:
      - db

  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - migrations
  db:
    image: postgres:16.1
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_ROOT}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - ./data:/var/lib/postgresql/data